version: "3"
services:
  node:
    build: ./node-service
    expose:
      - ${NODE_SERVER_PORT}
    networks:
      - webnet

      
  python:
    image: guifonte/python-service:latest
    ports:
      - "4001:80"
    networks:
      - webnet
networks:
  webnet:
