version: "3"
services:
  node:
    build: ./node-service
    ports:
      - "${NODE_SERVER_PORT}:3000"
  python:
    build: ./python-service
    ports:      
      - "${PYTHON_SERVER_PORT}:4000"
    depends_on:
      - redis
  redis:
    image: redis